image: Visual Studio 2017
branches:
    only:
      - master

environment:
  matrix:
  - target: x86_64-pc-windows-msvc
    VCVARS: '"c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"'
    channel: stable
  - target: i686-pc-windows-msvc
    VCVARS: '"c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"'
    channel: stable
  - target: x86_64-pc-windows-msvc
    VCVARS: '"c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"'
    channel: beta
  - target: i686-pc-windows-msvc
    VCVARS: '"c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"'
    channel: beta
  - target: x86_64-pc-windows-msvc
    VCVARS: '"c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"'
    channel: nightly
  - target: i686-pc-windows-msvc
    VCVARS: '"c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"'
    channel: nightly

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -V
  - cargo -V
  - call %VCVARS%

build: false

test_script:
  - cargo build
  - cargo test -j1
  - if [%channel%]==[nightly] (cargo update -Z minimal-versions)
  - if [%channel%]==[nightly] (cargo build)

matrix:
  allow_failures:
  - channel: nightly
