[package]
name = "c-ares-resolver"
license = "MIT"
version = "4.0.0"
authors = ["David Hotham"]
description = """
An asynchronous DNS resolver, backed by c-ares.
"""
repository = "https://github.com/dimbleby/c-ares-resolver"
documentation = "https://docs.rs/c-ares-resolver"
readme = "README.md"
keywords = ["DNS", "c-ares", "futures"]
categories = ["asynchronous", "network-programming"]

[dependencies]
c-ares = "5"
futures = "0.1"
mio-extras = "2"

[target.'cfg(unix)'.dependencies]
mio = "0.6"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winsock2"] }

[dev-dependencies]
tokio-core = "0.1"
